server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: hana-v
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    auth-code-expiration-millis: 300000  # 5분
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
  config: classpath:log4j2.xml
jwt:
  secret: ${JWT_SECRET_KEY:db308c664441568174c38810f78933ca3900393b46a4284f386f46d2a1b82bbb}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:300000}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:86400000}
fcm:
  google_application_credentials: hanav-3f6ee-firebase-adminsdk-2zr1j-876fa788ca.json
  url: https://fcm.googleapis.com/v1/projects/hanav-3f6ee/messages:send
cloud:
  aws:
    s3:
      bucket: ${S3_REGION:}
    stack.auto: false
    region.static: ${S3_REGION:}
    credentials:
      accessKey: ${S3_ACCESS_KEY:}
      secretKey: ${S3_SECRET_KEY:}