server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: hana-v
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      version: ${REDIS_VERSION}
      volume: ${REDIS_VOLUME}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    auth-code-expiration-millis: 300000  # 5분
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/hana-v-api.json
logging:
  level:
    root: ${LOGGING_LEVEL}
  config: classpath:log4j2.xml
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
