server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: hana-v
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
  show-sql: true
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/hana-v-api.json
logging:
  level:
    root: ${LOGGING_LEVEL}
  config: classpath:log4j2.xml