name: PR 테스트

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 패키지 캐시
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 빌드
        run: ./gradlew build

      - name: 포맷팅 검사
        run: ./gradlew spotlessCheck

      - name: 테스트 실행
        run: ./gradlew test
